# Artificial Neural Network

### Importing the libraries

In [27]:
import pandas as pd
import numpy as np

import tensorflow as tf

In [28]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [29]:
dataset=pd.read_excel("/content/Folds5x2_pp.xlsx")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values


In [30]:
print(X)


[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [31]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [33]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [34]:
ann.add(tf.keras.layers.Dense(units=6,activation = 'ReLU'))

### Adding the second hidden layer

In [35]:
ann.add(tf.keras.layers.Dense(units=6,activation = 'ReLU'))

### Adding the output layer

In [36]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [37]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN model on the Training set

In [41]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 16582.1992
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 137.2627
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 131.0800
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 123.4703
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 115.1061
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 105.8431
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 96.3501
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 86.9680
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 78.0093
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 69.6592
Epoch 11/100
240/240 [==============================] - 1s 3ms/step - loss: 62.2673
Epoch 12/100
240/240 [==============================] - 1s 3ms/step - loss: 5

### Predicting the results of the Test set

In [42]:
y_pred=ann.predict([[X_test]])
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 2ms/step
[[430.14 431.23]
 [461.17 460.01]
 [464.66 461.14]
 ...
 [471.9  473.26]
 [438.69 438.  ]
 [457.91 463.28]]
